image: Visual Studio 2019

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

install:	
  - choco install dotnet-sdk --version 5.0.100

environment:
  Appveyor: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet build Build.csproj -c Release /p:CI=true /p:GeneratePackageOnBuild=false
  - cmd: dotnet test Build.csproj -c Release /p:CI=true
  - cmd: dotnet pack Build.csproj --no-build -c Release /p:Packing=true /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/protobuf-net/api/v2
  on:
    branch: main
  api_key:
    secure: PV7ERAltWWLhy7AT2h+Vb5c1BM9/WFgvggb+rKyQ8hDg3fYqpZauYdidOOgt2lp4
  symbol_server: https://www.myget.org/F/protobuf-net/symbols/api/v2/package
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  on:
    branch: main
  api_key:
    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package
